config/routes.rb
HnClone::Application.routes.draw do

  
	[:comments, :stories].each do |resource|
		resources(resource) do
			resources :comments
		end
	end

  resources :users
  resources :votes, :only => [:create, :update]

  root :to => 'stories#index'

	## OmniAuth Sessions -- http://net.tutsplus.com/tutorials/ruby/how-to-use-omniauth-to-authenticate-your-users/
	get '/login', :to => 'sessions#new', :as => :login
	get '/logout', :to => 'sessions#destroy', :as => :logout

	match '/auth/:provider/callback', :to => 'sessions#create'
	match '/auth/failure', :to => 'sessions#failure'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user
	validates :provider, :uid, :presence => true

	def self.find_or_create(auth_hash)
	  unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
	    user = User.create :twitter_handle => auth_hash["extra"]["raw_info"]["screen_name"]
	    auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
	  end
	 
	  auth
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :body, :user_id, :parent_id, :parent_type

	belongs_to :user
	belongs_to :parent, :polymorphic => true
	has_many :comments, :as => :parent

	has_many :votes, :as => :target

	def story
		return @story if defined?(@story)
		@story = parent.is_a?(Story) ? parent : parent.story
	end
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
	validates :url, :uniqueness => true, :presence => true
end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :user
	has_many :votes, :as => :target
	has_many :comments, :as => :parent

	before_save :sentence_finisher
	validates :url, :uniqueness => true, :presence => true

	def votable_by?(user)
		!self.belongs_to?( user ) && !self.voted_on_by?( user )
	end

	def new?
		( Time.zone.now - self.created_at ).to_i < 900
	end

	def sentence_finisher
		self.title = self.title + "?" if self.title.match( /[^A-Z]$\b/ )
	end

	def belongs_to?(user)
		self.user == user
	end

	def voted_on_by?(user)
		self.votes.find_by_user_id( user.id )
	end

	def score
		self.upvotes.count - self.downvotes.count
	end

	def upvotes
		self.votes.where(:attitude => 'positive')
	end

	def downvotes
		self.votes.where(:attitude => 'negative')
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :authorizations
	has_many :stories
	has_many :votes
	has_many :comments
	validates :twitter_handle, :presence => true, :uniqueness => true


	def add_provider(auth_hash)
	  # Check if the provider already exists, so we don't add it twice
	  unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
	    Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
	  end
	end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	attr_accessible :target_id, :target_type, :attitude, :target

	belongs_to :target, :polymorphic => true
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :current_or_anonymous_user
  # Makes :current_user accessible to views

  def signed_in?
  	current_user
  end

  def current_or_anonymous_user
    current_user || anonymous_user
  end

  def current_user
  	@current_user ||= User.find( session[:user_id] ) if session[:user_id]
  end

  def anonymous_user
  	@anonymous_user ||= User.find_or_create_by_twitter_handle('anyofthemany')
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    redirect_to :root, :notice => "Please sign in." unless signed_in?
  end

  def correct_user
    user = Story.find( params[:id] ).user
    
    redirect_to :root, :notice => "That ain't yours." unless current_user?( user )
  end

  def time_limit_enforcement(story)
    redirect_to :root, :notice => "You're too late." unless story.new?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :get_parent, :only => [:create, :new]

	def index
		@comments = Comment.all
	end

	def create
		@comment = current_or_anonymous_user.comments.build params[:comment]
		@comment.parent = @parent
		@comment.save

		redirect_to story_path( @comment.story )
	end

	def new
		@comment = @parent
		@new_comment = Comment.new
	end

	protected

	def get_parent
		@parent = Story.find_by_id(params[:story_id]) if params[:story_id]
		@parent = Comment.find_by_id(params[:comment_id]) if params[:comment_id]

		redirect_to root_path unless defined?(@parent)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

	def create
	  auth_hash = request.env['omniauth.auth']
	 
	  if session[:user_id]
	    User.find( session[:user_id] ).add_provider( auth_hash )
	 
	    redirect_to :root
	    flash[:success] = "You can now login using #{ auth_hash[ "provider" ].capitalize } too!"
	  else
	    auth = Authorization.find_or_create( auth_hash )
	 
	    session[:user_id] = auth.user_id
	 
	    redirect_to :root
	    flash[:success] = "Welcome to Hackifesto, @#{ User.find( session[:user_id] ).twitter_handle }!"
	  end
	end

  def failure
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to :root
  	flash[:success] = "You've logged out!"
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_filter :signed_in_user, :only => [:edit, :update]
	before_filter :correct_user, :only => [:edit, :update]
	before_filter :find_id, :only => [:edit, :update, :show]


	def index
		@stories = Story.page( params[:page] )
		@story   = Story.new
	end


	def create
		@story      	= Story.new( params[:story] )
		@story.user 	= current_user || anonymous_user

		heidegger 		= "Making itself intelligible is suicide for philosophy. But not for stories, stupid."
		flash[:error] = heidegger unless @story.save

		redirect_to :root
	end


	def new
		@story = Story.new
	end


	def update
		@story.update_attributes( params[:story] )

		redirect_to :root
	end


	def show
		@comment = Comment.new
		@story = Story.find( params[:id] )
		# @story.comments.build( @comment )
	end


	def edit	 
		time_limit_enforcement( @story )
	end
	

	private

	def find_id
		@story = Story.find( params[:id] )
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


	def create
		current_user = anonymous_user unless current_user
		@story = Story.find_by_id( params[:target_id] )

		@vote = current_user.votes.find_or_create_by_target_id( @story.id )
		@vote.attitude = params[:attitude]
		@vote.target_type = params[:target_type]

		@vote.save
	end

	def update
		@vote = current_user.votes.find_by_id( params[:vote][:id] )
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(validation_outcome)
    case validation_outcome
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
	def url_with_protocol(url)
		/^http/.match( url ) ? url : "http://#{ url }"
	end
end

app/helpers/votes_helper.rb
module VotesHelper
	def vote_params(attitude, target)

		case attitude
		when :positive
			{:target_id => target.id, :target_type => "Story", :attitude => "positive"}
		when :negative			
			{:target_id => target.id, :target_type => "Story", :attitude => "positive"}
		end

	end
end

app/views/comments/_comment.html.erb
<li class="comment">
	<p>
		<span>
			<%= comment.body %>
		</span> 
		<span>
			--@<%= User.find_by_id(comment.user_id).twitter_handle %>
		</span>

		<%= link_to "Reply", new_comment_comment_path(comment), :class => "reply_comment_link" %>
	</p>

	<% unless comment.comments.empty? %>
		<ol class="comment_list">
			<%= render :partial => 'comments/comment', :collection => comment.comments %>
		</ol>
	<% end %>
</li>

app/views/comments/index.html.erb
<ul>
	<% @comments.each do |comment| %>
	<li>
		<ul>
			<li><%= "Body: #{comment.body}" %></li>
			<li><%= "User: #{comment.user}" %></li>
			<li><%= "Parent: #{comment.parent}" %></li>
		</ul>
		<br>
	<% end %>
</ul>

app/views/comments/new.html.erb
<h3><%= @comment.body %></h3>

<%= form_for [@comment, @new_comment] do |f| %>
	<%= f.text_area :body %>
	<%= f.submit "Comment!" %>
<% end -%>

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href=<%= root_path %> dta-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner header">
    <div class="container">
      <%= link_to 'hackifesto', root_path, :class => "brand" %>
        <ul class="nav pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <% if current_user %>
              <li id="fat-menu" class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                  Welcome, @<%= current_user.twitter_handle %>!
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" id="fat">              
                  <li><%= link_to "Sign Out", logout_path %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in with Twitter", "/auth/twitter" %></li>
          <% end -%>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackifesto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container main_content">
		<div class="row">
			<%= render 'layouts/flash_messages' %>
			
			<%= yield %>		
		</div>
	</div>

</body>
</html>

app/views/links/_form.html.erb
<div class="span4">
	<div class="sidebar">
		<%= form_for(@link) do |f|%>

			<%= f.text_field :title,:placeholder => "Title" %>
			<%= f.text_field :url, :placeholder => "URL" %>

			<%= f.submit :class => "btn submit_button" %>
		<% end -%>
	</div>
</div>	

app/views/links/edit.html.erb
<div class="span6 offset3">
	<%= form_for(@link, :html => {:class => "form-horizontal"}) do |f| %>

		<%= f.text_field :title,:placeholder => "Title" %>
		<%= f.text_field :url, :placeholder => "URL" %>

		<%= f.submit :class => "btn submit_button" %>
	<% end -%>
</div>

app/views/stories/_ballot.html.erb
<% if target.votable_by?( current_or_anonymous_user ) %>
	<%= link_to   'up', votes_path( vote_params( :positive, target ) ), :remote => true, :method => :post %>
	<%= link_to 'down', votes_path( vote_params( :negative, target ) ), :remote => true, :method => :post %>
<% end %>

app/views/stories/_entry.html.erb
<li class="single_entry">
	<ul>
		<li>
			<h3 class="inline">
				<span id="story_<%= story.id %>_votes"><%= story.score %></span>
				
				<%= link_to story.title, url_with_protocol( story.url ), :target => '_blank' %>

				<%= render 'ballot', :target => story %>

			</h3>

			<% if story.new? && story.belongs_to?(current_or_anonymous_user) %>
				<%= link_to "edit", edit_story_path( story ), :class => "hover_hidden pull-right edit_button" %>
			<% end %>

		</li>

		<li>
						<%= "#{story.url} via @#{story.user.twitter_handle}" %>
						<%= link_to "SHOW", story_path(story) %>
		</li>
	</ul>
</li>

app/views/stories/_form.html.erb
<div class="span4">
	<div class="sidebar">
		<%= form_for( @story ) do |f| %>

			<%= f.text_field :title,:placeholder => "Title" %>
			<%= f.text_field :url, :placeholder => "URL" %>

			<%= f.submit :class => "btn submit_button" %>
		<% end -%>
	</div>
</div>	

app/views/stories/create.js.erb
var entry = "<% j(render 'entry', :story=> @story %>";
$('#new_entries').prepend(entry);
alert('here we go');

app/views/stories/edit.html.erb
<div class="span6 offset3">
	<%= form_for( @story, :html => {:class => "form-horizontal"}) do |f| %>

		<%= f.text_field :title,:placeholder => "Title" %>
		<%= f.text_field :url, :placeholder => "URL" %>

		<%= f.submit :class => "btn submit_button" %>
	<% end -%>
</div>

app/views/stories/index.html.erb
<div class="span8">
	<ol id="new_entries">
		<% @stories.each do |story| %>
			 <%= render 'entry', :story => story %>
		<% end -%>
	</ol>

	<%= paginate @stories %>
</div>

<%= render 'form' %>

app/views/stories/show.html.erb
<section class="story">
	<%= render 'entry', :story => @story%>
</section>

<section class="comments">
	<h3>Comments</h3>

	<%= form_for [@story, @comment] do |f| %>
		<%= f.text_area :body %>
		<%= f.submit "Comment!" %>
	<% end -%>
	
	<ol>
		<%= render @story.comments %>
	</ol>
</section>

app/views/votes/create.js.erb
var obj = $("#story_<%= @story.id %>_votes");
var change = function(value){
	obj.text( parseInt( obj.text() ) + value )
}


if ('<%= params[:attitude] %>' == 'positive'){
	change(1);
} else {
	change(-1);
}